SMS_URL: "http://sms.messageindia.in/sendSMS?username=growwcapital&sendername=GROCAP&smstype=TRANS&apikey=ffc1c03a-1c0f-42a8-bcf7-3478db32c01f"
# SMS_API_KEY: "ffc1c03a-1c0f-42a8-bcf7-3478db32c01f"
# &numbers=9370205657
# &message=Hi Bro