default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: mYPASS#432i
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: getCapital_development
# production:
#   <<: *default
#   database: getCapital_production
